secure_input_notification: false
matches:
  - trigger: ";d"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y%m%d"
  - trigger: ";t"
    replace: "{{mydatetime}}"
    vars:
      - name: mydatetime
        type: date
        params:
          format: "%Y%m%d%H%M%S"
