(key-chord-define-global "0o" ")")
;; Sadly, "1q" is impossible to hit on my keyboard.
(key-chord-define-global "1q" "!")
(key-chord-define-global "2w" "@")
(key-chord-define-global "3e" "#")
(key-chord-define-global "4r" "$")
(key-chord-define-global "5t" "%")
(key-chord-define-global "6y" "^")
(key-chord-define-global "6t" "^")
(key-chord-define-global "7y" "&")
(key-chord-define-global "8u" "*")
(key-chord-define-global "9i" "(")
(key-chord-define-global "-p" "_")
(key-chord-define-global ";;" "\C-e;")
(key-chord-define-global "fg" 'iy-go-to-char)
(key-chord-define-global "df" 'iy-go-to-char-backward)

(key-chord-define emacs-lisp-mode-map
                  "7y" "&optional ")
(key-chord-mode 1)
