;; (setq web-mode-markup-indent-offset 2)
(setq web-mode-css-indent-offset 2)
;; (setq web-mode-code-indent-offset 2)
;; (setq web-mode-attr-indent-offset 2)
;; (setq web-mode-attr-value-indent-offset 2)
;; (setq web-mode-indentless-elements 2)
(setq web-mode-markup-indent-offset 2)
;; (setq web-mode-sql-indent-offset 2)
(setq web-mode-script-padding 2)
(setq web-mode-style-padding 2)
(setq web-mode-block-padding 2)

;; (add-hook 'css-mode-hook (lambda ()
;;                            (setq web-mode-markup-indent-offset 2)
;;                            (setq web-mode-css-indent-offset 2)
;;                            (setq web-mode-code-indent-offset 2)
;;                            (setq web-mode-attr-indent-offset 2)
;;                            (setq web-mode-attr-value-indent-offset 2)
;;                            (setq web-mode-indentless-elements 2)
;;                            (setq web-mode-markup-indent-offset 2)
;;                            (setq web-mode-sql-indent-offset 2)
;;                            (setq web-mode-script-padding 2)
;;                            (setq web-mode-style-padding 2)
;;                            (setq web-mode-block-padding 2)
;;                            ))
